[
    {code: "MX", value:1, name: "Mehhiko"},
    {code: "EG", value:1, name: "Egiptus"},
    {code: "ET", value:1, name: "Etioopia"},
    {code: "MC", value:1, name: "Monaco"},
    {code: "PH", value:1, name: "Filipiinid"},
    {code: "PR", value:1, name: "Puerto Rico"},
    {code: "AZ", value:1, name: "Azerbaijan"},
    {code: "GE", value:1, name: "Gruusia"},
    {code: "CL", value:1, name: "Tšiili"},
    {code: "MH", value:1, name: "Marshall Islands"},
    {code: "BD", value:1, name: "Bangladesh"},
    {code: "GA", value:1, name: "Gabon"},
    {code: "MD", value:1, name: "Moldova"},
    {code: "GQ", value:1, name: "Ekvatoriaal-Guinea"},
    {code: "LK", value:1, name: "Sri Lanka"},
    {code: "AM", value:1, name: "Armeenia"},
    {code: "SA", value:1, name: "Saudi-Araabia"},
    {code: "AD", value:1, name: "Andorra"},
    {code: "BZ", value:1, name: "Belize"},
    {code: "IO", value:2, name: "Briti India ookeani ala"},
    {code: "ME", value:2, name: "Montenegro"},
    {code: "PK", value:2, name: "Pakistan"},
    {code: "QA", value:2, name: "Katar"},
    {code: "EC", value:2, name: "Ecuador"},
    {code: "CR", value:3, name: "Costa Rica"},
    {code: "JE", value:3, name: "Jersey"},
    {code: "LI", value:3, name: "Liechtenstein"},
    {code: "PA", value:3, name: "Panama"},
    {code: "ID", value:3, name: "Indonesia"},
    {code: "LY", value:3, name: "Liibüa"},
    {code: "VN", value:3, name: "Vietnam"},
    {code: "AG", value:4, name: "Antigua ja Barbuda"},
    {code: "AN", value:4, name: "Hollandi Antillid"},
    {code: "IS", value:4, name: "Island"},
    {code: "AF", value:4, name: "Afganistan"},
    {code: "HR", value:4, name: "Horvaatia"},
    {code: "SC", value:7, name: "Seychelles"},
    {code: "TH", value:7, name: "Tai"},
    {code: "AR", value:7, name: "Argentiina"},
    {code: "GI", value:8, name: "Gibraltar"},
    {code: "MY", value:8, name: "Malaisia"},
    {code: "KR", value:9, name: "Korea Vabariik"},
    {code: "AE", value:9, name: "Araabia Ühendemiraadid"},
    {code: "TW", value:10, name: "Taiwan"},
    {code: "SI", value:10, name: "Sloveenia"},
    {code: "NZ", value:11, name: "Uus-Meremaa"},
    {code: "ZA", value:12, name: "Lõuna-Aafrika Vabariik"},
    {code: "BG", value:13, name: "Bulgaaria"},
    {code: "VG", value:13, name: "Virgin Islands, British"},
    {code: "IN", value:13, name: "India"},
    {code: "IL", value:14, name: "Iisrael"},
    {code: "SG", value:15, name: "Singapur"},
    {code: "UA", value:18, name: "Ukraina"},
    {code: "RO", value:18, name: "Rumeenia"},
    {code: "BR", value:19, name: "Brasiilia"},
    {code: "BM", value:20, name: "Bermuda"},
    {code: "HK", value:22, name: "Hong Kong"},
    {code: "HU", value:25, name: "Ungari"},
    {code: "PT", value:25, name: "Portugal"},
    {code: "TR", value:28, name: "Türgi"},
    {code: "IE", value:29, name: "Iirimaa"},
    {code: "CY", value:29, name: "Küpros"},
    {code: "SK", value:33, name: "Slovakkia"},
    {code: "MT", value:39, name: "Malta"},
    {code: "JP", value:42, name: "Jaapan"},
    {code: "GR", value:50, name: "Kreeka"},
    {code: "IM", value:53, name: "Mani saar"},
    {code: "BY", value:54, name: "Valgevene"},
    {code: "AU", value:59, name: "Austraalia"},
    {code: "CN", value:62, name: "Hiina"},
    {code: "CA", value:67, name: "Kanada"},
    {code: "CZ", value:71, name: "Tšehhi"},
    {code: "LU", value:72, name: "Luksemburg"},
    {code: "ES", value:75, name: "Hispaania"},
    {code: "AT", value:76, name: "Austria"},
    {code: "BE", value:85, name: "Belgia"},
    {code: "NO", value:104, name: "Norra"},
    {code: "RU", value:124, name: "Venemaa"},
    {code: "IT", value:127, name: "Itaalia"},
    {code: "DK", value:217, name: "Taani"},
    {code: "CH", value:223, name: "Šveits"},
    {code: "PL", value:234, name: "Poola"},
    {code: "NL", value:295, name: "Holland"},
    {code: "FR", value:315, name: "Prantsusmaa"},
    {code: "FI", value:499, name: "Soome"},
    {code: "LV", value:609, name: "Läti"},
    {code: "SE", value:664, name: "Rootsi"},
    {code: "LT", value:666, name: "Leedu"},
    {code: "GB", value:732, name: "Suurbritannia"},
    {code: "DE", value:830, name: "Saksamaa"},
    {code: "US", value:1268, name: "Ameerika Ühendriigid"},
    {code: "EE", value:73338, name: "Eesti"}
]
